<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDeTnXhx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDeTnXhx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDeTnXhx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDeTnXhx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDeTnXhx\App_KernelDevDebugContainer([
    'container.build_hash' => 'DeTnXhx',
    'container.build_id' => '12b6258f',
    'container.build_time' => 1726853569,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDeTnXhx');
